#pragma once

#include <Shape.h>
#include <vector>
#include <cassert>
#include <cstddef> 
#include <iostream>
#include <algorithm>
#include <numeric>
#include <execution>
#include <cmath>

namespace nerd {

template <typename Type>
class Tensor {
  private:

    /*
     * shape - dimensions the tensor takes on 
     * data - self explanatory
     * strides - helps w/ indexing in the tensor the inner workings of it are funky
     */
    Shape shape;
    std::vector<Type> data;
    Shape strides;    

    // computing strides to help with multidim indexing
    Shape compute_strides() const {
      Shape strides(shape.rank());
      for (int i = shape.rank() - 2; i >= 0; --i ) {
        strides[i] = strides[i + 1] * shape[i + 1];
      }
      return strides;
    }

    /*
     * the following two functions were (unfortunately) generated by ChatGPT
     */

    // returns flat index of data via strides
    std::size_t flat_index(const std::vector<std::size_t>& indices) const {
      assert(indices.size() == shape.rank());

      std::size_t index = 0;
      for (std::size_t i = 0; i < indices.size(); ++i) {
        assert(indices[i] < shape[i]);
        index += indices[i] * strides[i];
      }
      return index;
    }

    // helper printing function, takes into account varying dimensions, thus nesting bracketss where necessary
    void print_recursive(
        std::ostream& os,
        std::size_t dim,
        std::size_t offset,
        std::size_t indent
    ) const
    {
        std::string spacing(indent, ' ');
        os << spacing << "[\n";
        // Last dimension: print values
        if (dim == shape.rank() - 1)
        {
            os << spacing << " ";
            for (std::size_t i = 0; i < shape[dim]; ++i)
            {
                os << data[offset + i * strides[dim]];
                if (i + 1 < shape[dim])
                    os << ", ";
            }
        }
        else
        {
            for (std::size_t i = 0; i < shape[dim]; ++i)
            {
                print_recursive(
                    os,
                    dim + 1,
                    offset + i * strides[dim],
                    indent + 2
                );
                if (i + 1 < shape[dim])
                    os << ",\n";
            }
        }
        os << "\n" << spacing << "]";
    }

  public:

    /* 
     * Constructors and factory functions
     */

    // empty constructor
    Tensor() = default;

    // takes in shape, data is initialized as zeros
    Tensor(const Shape& shape)
      : shape(shape), data(shape.size()) {
        strides = compute_strides();
      }

    // takes and shape, makes data some uniform inputted value 
    Tensor(const Shape& shape, const Type& val)
      : shape(shape), data(shape.size(), val) {
        strides = compute_strides();
      } 
  
    // returns tensor of 0s
    static Tensor zeros(const Shape& shape) {
      return Tensor(shape, 0);
    }

    // returns tensors of 1s
    static Tensor ones(const Shape& shape) {
      return Tensor(shape, 1);
    }

    // returns identity matrix
    static Tensor identity(std::size_t dim) {
      Tensor<Type> res(Shape{dim, dim});
      for (std::size_t i = 0; i < dim; ++i) {
        res.data[i * dim + i] = Type{1};
      }
      return res;
    }

    // returns diagonal matrix of inputs
    static Tensor diagonal(const std::vector<Type>& arr) {
      std::size_t dim = arr.size();
      Tensor<Type> res(Shape{dim, dim});
      for (std::size_t i = 0; i < dim; ++i) {
        res.data[i * dim + i] = arr[i];
      }
      return res;
    }

    /*
     * Accesing data and data at index + printing
     */

    // For modification of data 
    Type& operator[](std::size_t i) {
      assert(i < data.size());
      return data[i];
    }

    // For reading data
    const Type& operator[](std::size_t i) const {
      assert(i < data.size());
      return data[i];
    }

    // Another helper print thingy
    void print(std::ostream& os) const {
        print_recursive(os, 0, 0, 0);
    }

    // For modification w/ multidimensional indexing
    Type& operator()(const std::vector<std::size_t>& indices) {
      return data[flat_index(indices)];
    }

    // Read only version of operator above 
    const Type& operator()(const std::vector<std::size_t>& indices) const {
      return data[flat_index(indices)];
    }    

    // NOTE -- DO NOT USE THIS ABOVE 3-4 DIMENSIONS IT IS PRACTICALLY UNREADABLE
    friend std::ostream& operator<<(std::ostream& os, const Tensor& tensor) {
      tensor.print(os);
      return os;
    }

    /* 
     * Tensor arithmetic
     */

    // Modification by addition
    Tensor& operator+=(const Tensor& other) {
      assert(same_shape(other));
      for (std::size_t i = 0; i < data.size(); ++i) {
        data[i] += other.data[i];
      }
      return *this;
    }

    // Creates another tensor via addition
    Tensor operator+(const Tensor& other) const {
      Tensor res = *this;
      res += other;
      return res;
    }

    // Modification by subtraction
    Tensor& operator-=(const Tensor& other) {
      assert(same_shape(other));
      for (std::size_t i = 0; i < data.size(); ++i) {
        data[i] -= other.data[i];
      }
      return *this;
    }

    // Creates another tensor via subtraction
    Tensor operator-(const Tensor& other) const {
      Tensor res = *this;
      res -= other;
      return res;
    }

    // Modifies tensor via scalar multiplication
    Tensor& operator*=(const Type& n) {
      for (Type& x : data) {
        x *= n;
      }
      return *this;
    }

    // Creates another tensor via scalar multiplication
    Tensor operator*(const Type& n) const {
      Tensor res = *this;
      res *= n;
      return res;
    }

    // and below is scalar division
    Tensor& operator/=(const Type& n) {
      for (Type& x : data) {
        x /= n;
      }
      return *this;
    }

    Tensor operator/(const Type& n) const {
      Tensor res = *this;
      res /= n;
      return res;
    }

    /*
     * Generic Tensor Manipulation
     */

    Tensor m_transpose() const {
      assert(ndim() == 2);
      Tensor res(Shape{shape[1], shape[0]});
      for (std::size_t i = 0; i < shape[1]; ++i) {
        for (std::size_t j = 0; j < shape[0]; ++j) {
          res({i, j}) = (*this)({j, i});
        }
      }
      return res;
    }

    Tensor reshape(const Shape& other) const {
      assert(shape.size() == other.size());
      Tensor res = *this;
      res.shape = other;
      res.strides = res.compute_strides();
      return res;
    }

    Tensor flatten() const {
      return reshape({size()});
    }

    Tensor squeeze() const {
      Tensor res = *this;
      res.shape.remove();
      res.strides = res.compute_strides();
      return res;
    }

    Tensor unsqueeze(std::size_t index) const {
      Tensor res = *this;
      res.shape.add(index, 1);
      res.strides = res.compute_strides();
      return res;
    }

    Tensor permute(const std::vector<std::size_t>& other) const {
      assert(shape.rank() == other.size());
      Tensor res(*this);
      for (std::size_t i = 0; i < other.size(); ++i) {
        res.shape[i] = this->shape[other[i]];
        res.strides[i] = this->strides[other[i]];
      }
      return res;
    }

    /* 
     * Tensor Reductions and Statistics via computation
     */

    Type sum() const {
      assert(!empty());
      return std::accumulate(begin(), end(), Type{0}); 
    }

    double mean() const {
      assert(!empty());
      return sum() / size();
    }

    double stdev() const {
      assert(!empty());
      return std::sqrt(var());
    }

    double var() const {
      assert(!empty());
      double _mean = mean();
      double sqrd_diff_sum = 0.0;
      for (const auto& x : *this) {
        double diff = x - _mean;
        sqrd_diff_sum += diff * diff;
      }
      return sqrd_diff_sum / size();
    }

    Type min() const {
      assert(!empty());
      auto min_it = std::min_element(begin(), end());
      return *min_it;
    }

    Type max() const {
      assert(!empty());
      auto max_it = std::max_element(begin(), end());
      return *max_it;
    }

    /*
     *  Iterators
     */

    auto begin() {
      return data.begin();
    }

    auto end() {
      return data.end();
    }

    auto begin() const {
      return data.begin();
    }

    auto end() const {
      return data.end();
    }

    // Fills tensor w/ inputted value
    void fill(const Type& T) {
      for (auto& x : data) {
        x = T;
      }
    }

    // Checks if a tensor has elements
    bool empty() const {
      return data.empty();
    }

    // Checks if a tensor has the same shape as another tensor
    bool same_shape(const Tensor& other) const {
      return shape == other.shape;
    }

    /* 
     * Getter functions
     */ 

    // Returns shape of tensor
    const Shape& get_shape() const {
      return shape;
    }

    // Returns strides of a tensors dimensions
    const Shape& get_strides() const {
      return strides;
    }

    std::size_t ndim() const {
      return shape.ndim();
    }

    // Returns size of tensor/number of elements 
    std::size_t size() const {
      return shape.size();
    }
};
  
}
