#pragma once

#include <Shape.h>
#include <vector>
#include <cassert>
#include <cstddef> 
#include <iostream>

namespace nerd {

template <typename Type>
class Tensor {
  private:

    Shape shape;
    std::vector<Type> data;
    Shape strides;    

    // computing strides to help with multidim indexing
    Shape compute_strides() {
      Shape strides(shape.rank());

      for (int i = shape.rank() - 2; i >= 0; --i ) {
        strides[i] = strides[i + 1] * shape[i + 1];
      }

      return strides;
    }

    // the following two functions were (unfortunately) generated by ChatGPT

    // returns flat index of data via strides
    std::size_t flat_index(const std::vector<std::size_t>& indices) const {
      assert(indices.size() == shape.rank());

      std::size_t index = 0;

      for (std::size_t i = 0; i < indices.size(); ++i) {
        assert(indices[i] < shape[i]);
        index += indices[i] * strides[i];
      }

      return index;
    }

    // helper printing function, takes into account varying dimensiosn 
    void print_recursive(
        std::ostream& os,
        std::size_t dim,
        std::size_t offset,
        std::size_t indent
    ) const
    {
        std::string spacing(indent, ' ');
        os << spacing << "[\n";
        // Last dimension: print values
        if (dim == shape.rank() - 1)
        {
            os << spacing << " ";
            for (std::size_t i = 0; i < shape[dim]; ++i)
            {
                os << data[offset + i * strides[dim]];
                if (i + 1 < shape[dim])
                    os << ", ";
            }
        }
        else
        {
            for (std::size_t i = 0; i < shape[dim]; ++i)
            {
                print_recursive(
                    os,
                    dim + 1,
                    offset + i * strides[dim],
                    indent + 2
                );
                if (i + 1 < shape[dim])
                    os << ",\n";
            }
        }
        os << "\n" << spacing << "]";
    }

  public:

    /* 
     * Constructors and factory functions
     */

    // empty constructor
    Tensor() = default;

    // takes in shape, data is initialized as zeros
    Tensor(const Shape& shape)
      : shape(shape), data(shape.size()) {
        strides = compute_strides();
      }

    // takes and shape, makes data some uniform inputted value 
    Tensor(const Shape& shape, const Type& val)
      : shape(shape), data(shape.size(), val) {
        strides = compute_strides();
      } 
  
    // returns tensor of 0s
    static Tensor zeros(const Shape& shape) {
      return Tensor(shape, 0);
    }

    // returns tensors of 1s
    static Tensor ones(const Shape& shape) {
      return Tensor(shape, 1);
    }

    // returns identity matrix
    static Tensor identity(std::size_t dim) {
      Tensor<Type> res(Shape{dim, dim});
      for (std::size_t i = 0; i < dim; ++i) {
        res.data[i * dim + i] = Type{1};
      }
      return res;
    }

    // returns diagonal matrix of inputs
    static Tensor diagonal(const std::vector<Type>& arr) {
      std::size_t dim = arr.size();
      Tensor<Type> res(Shape{dim, dim});
      for (std::size_t i = 0; i < dim; ++i) {
        res.data[i * dim + i] = arr[i];
      }
      return res;
    }

    /*
     * Accesing data and data at index + printing
     */

    Type& operator[](std::size_t i) {
      assert(i < data.size());
      return data[i];
    }

    void print(std::ostream& os) const {
        print_recursive(os, 0, 0, 0);
    }

    const Type& operator[](std::size_t i) const {
      assert(i < data.size());
      return data[i];
    }

    Type& operator()(const std::vector<std::size_t>& indices) {
      return data[flat_index(indices)];
    }

    const Type& operator()(const std::vector<std::size_t>& indices) const {
      return data[flat_index(indices)];
    }    

    // NOTE -- DO NOT USE THIS ABOVE 3-4 DIMENSIONS IT IS PRACTICALLY UNREADABLE
    friend std::ostream& operator<<(std::ostream& os, const Tensor& tensor) {
      tensor.print(os);
      return os;
    }

    /* 
     * Tensor arithmetic
     */

    // Modification by addition
    Tensor& operator+=(const Tensor& other) {
      assert(same_shape(other));
      for (std::size_t i = 0; i < data.size(); ++i) {
        data[i] += other.data[i];
      }
      return *this;
    }

    // Creates another matrix via addition
    Tensor operator+(const Tensor& other) const {
      Tensor res = *this;
      res += other;
      return res;
    }

    // Modification by subtraction
    Tensor& operator-=(const Tensor& other) {
      assert(same_shape(other));
      for (std::size_t i = 0; i < data.size(); ++i) {
        data[i] -= other.data[i];
      }
      return *this;
    }

    // Creates another matrix via subtraction
    Tensor operator-(const Tensor& other) const {
      Tensor res = *this;
      res -= other;
      return res;
    }

    Tensor& operator*=(const Type& n) {
      for (Type& x : data) {
        x *= n;
      }
      return *this;
    }

    // Creates another matrix via scalar multiplication
    Tensor operator*(const Type& n) const {
      Tensor res = *this;
      res *= n;
      return res;
    }

    // and below is scalar division
    Tensor& operator/=(const Type& n) {
      for (Type& x : data) {
        x /= n;
      }
      return *this;
    }

    Tensor operator/(const Type& n) const {
      Tensor res = *this;
      res /= n;
      return res;
    }

    /*
     *  Iterators
     */
    auto begin() {
      return data.begin();
    }

    auto end() {
      return data.end();
    }
    auto begin() const {
      return data.begin();
    }

    auto end() const {
      return data.end();
    }

    void fill(const Type& T) {
      for (auto& x : data) {
        x = T;
      }
    }

    bool empty() {
      return data.empty();
    }

    bool same_shape(const Tensor& other) const {
      return shape == other.shape;
    }

    /* 
     * getter functions
     */ 

    // return shape of tensor
    const Shape& get_shape() const {
      return shape;
    }

    const Shape get_strides() const {
      return strides;
    }

    // return size of tensor/number of elements 
    std::size_t size() const {
      return shape.size();
    }
};
  
}
