#pragma once

#include <Shape.h>
#include <vector>
#include <cassert>
#include <iostream>

namespace nerd {

template <typename Type>
class Tensor {
  private:

    Shape shape;
    std::vector<Type> data;
    Shape strides;    

    Shape compute_strides() {
      Shape strides(shape.rank());

      for (int i = shape.rank() - 2; i >= 0; --i ) {
        strides[i] = strides[i + 1] * shape[i + 1];
      }

      return strides;
    }

    // the following two functions were (unfortunately) generated by ChatGPT
    std::size_t flat_index(const std::vector<std::size_t>& indices) const {
      assert(indices.size() == shape.rank());

      std::size_t index = 0;

      for (std::size_t i = 0; i < indices.size(); ++i) {
        assert(indices[i] < shape[i]);
        index += indices[i] * strides[i];
      }

      return index;
    }

    void print_recursive(
        std::ostream& os,
        std::size_t dimension,
        std::size_t offset
    ) const {

        if (dimension == shape.rank()-1) {

            os << "[";

            for(std::size_t i = 0; i < shape[dimension]; ++i) {

                os << data[offset + i * strides[dimension]];

                if(i + 1 < shape[dimension])
                    os << ", ";
            }

            os << "]";

            return;
        }


        os << "\n[";

        for(std::size_t i = 0; i < shape[dimension]; ++i) {

            print_recursive(
                os,
                dimension + 1,
                offset + i * strides[dimension]
            );

            if(i + 1 < shape[dimension])
                os << ",\n";
        }

        os << "]\n";
    }

  public:

    Tensor() = default;

    Tensor(const Shape& shape, const Type& val)
      : shape(shape), data(shape.size(), val) {
        strides = compute_strides();
      } 
  
    Type& operator[](std::size_t i) {
      assert(i < data.size());
      return data[i];
    }

    void print(std::ostream& os) const {
        print_recursive(os, 0, 0);
    }

    const Type& operator[](std::size_t i) const {
      assert(i < data.size());
      return data[i];
    }

    Type& operator()(const std::vector<std::size_t>& indices) {
      return data[flat_index(indices)];
    }

    const Type& operator()(const std::vector<std::size_t>& indices) const {
      return data[flat_index(indices)];
    }    

    friend std::ostream& operator<<(std::ostream& os, const Tensor& tensor) {
      tensor.print(os);
      return os;
    }

  /*
   * Iterators
   */
    auto begin() {
      return data.begin();
    }

    auto end() {
      return data.end();
    }
    auto begin() const {
      return data.begin();
    }

    auto end() const {
      return data.end();
    }

    void fill(const Type& T) {
      for (auto& x : data) {
        x = T;
      }
    }

    bool empty() {
      return data.empty();
    }

    bool same_shape(Tensor& other) {
      return shape == other.shape;
    }

    /* 
     * getter functions
     */ 

    // return shape of tensor
    const Shape& get_shape() const {
      return shape;
    }

    const Shape get_strides() const {
      return strides;
    }


    // return size of tensor/number of elements 
    std::size_t size() const {
      return shape.size();
    }
};
  
}
